### ISSUE TITLE
RSS/ATOM Feeds

### ISSUE THREAD

**Issue by mizhozan** [ahappyphd/ahappyphd.github.io#1]
Thanks for your blog, but as far as I searched, I couldn't find an RSS (or alike) link. I'm consuming blog contents using feed readers, and it would be great if this interesting blog add one.

**Comment by ahappyphd** [comment]
Hi @mizhozan , thanks a lot for the issue!
There is actually an RSS feed: https://ahappyphd.org/index.xml
... but it is not immediately obvious where it is (my feed reader detected it automatically, so I assumed others would as well). Sorry!

I will anyways add a link in the front page.

**Comment by ahappyphd** [comment]
Solved with [3ed802](https://github.com/ahappyphd/ahappyphd.github.io/commit/3ed802c1cb4addb855805d1372522e4879c45ca7)
